server:
  port: 9002
springdoc:
  swagger-ui:
    path=/swagger-ui.html

---
spring:
  config:
        activate:
            on-profile: default
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/naton
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    database: postgresql

---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:h2:./test;INIT=CREATE SCHEMA IF NOT EXISTS PURCHASEOWNER;MODE=MySQL;
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        hibernate.dialect: org.hibernate.dialect.H2Dialect
        hibernate.hbm2ddl.auto: create-drop